import Head from 'next/head';

export default function pages_profile() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>ptherpage</h1>
      </main>
    </div>
  );
}
