import Head from 'next/head';
import Image from 'next/image';
import { Comps_hello } from '#src/Comps/hello';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Comps_hello />
      </main>
    </div>
  );
}
