import Head from 'next/head';
import {
  Comps_carousel,
  Comps_hero,
  Comps_misc_placeholder,
  Comps_testcomp,
  Comps_features,
} from '#src/Comps';

export default function Home() {
  return (
    <div>
      <Comps_hero />
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Comps_misc_placeholder>
          <p>Hello Worlddd</p>
        </Comps_misc_placeholder>
        <Comps_testcomp />
        <Comps_carousel />
      </main>
      <Comps_features />
    </div>
  );
}
